[dataset]
name = "E-ANND-5"
cell_type_col = "celltype_annotation"
doublet_col = "predicted_doublets"
mito_col = "mito"
is_normalised= true
apply_mapping = true


[pca]
n_components = 2500
incremental = false
gpu = false

[xgboost]
n_estimators = 500
max_depth = 6
subsample = 0.9
colsample_bytree = 0.9
learning_rate = 0.05
reg_alpha = 1.0
reg_lambda = 1.0
early_stopping_rounds = 10

[vae]
batch_size = 5000
num_epochs = 100
train_workers = 16
val_workers = 8

[io]
output_dir = "results"